### PR TITLE
limit github pipelines to run only on main repo

### PR DESCRIPTION
**Pull request by beniamin**
### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Some devs reported they receive pipeline execution failes emails when they update their fork development branch.

This repo prevent deploy pipeline to run on forks.

### How has it been tested?

Please describe the tests that you ran to verify your changes.

### CODE REVIEW

**Comment by andreiio** [comment]
N-ar trebui să primească mailuri, că this only runs on tags. Can we get a screenshot cu un mail primit?

**Comment by beniamin** [comment]
Screenshot 2022-03-02 at 21 55 35

Se intampla doar cand isi actualizeaza propriul development.

**Comment by andreiio** [comment]
Ok, atunci trebuie modificat `deploy-staging.yaml`, nu prod.

**Comment by beniamin** [comment]
> Ok, atunci trebuie modificat `deploy-staging.yaml`, nu prod.

done

**Review by andreiio — APPROVED** [review]

**Pull request merged**
