### PR TITLE
Remove number of guests limitation for housing

### PR DESCRIPTION
**Pull request by sherbastian**
### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Closes https://github.com/code4romania/war-support-un-acoperis/issues/144

Please mention the main changes this PR brings.

### How has it been tested?

Please describe the tests that you ran to verify your changes.

### CODE REVIEW

**Comment by gheorghelupu17** [comment]
E posibil sa crape sql de la acel change... @andreiio  poți verifica că nu da 502 dacă îi dăm deploy pls ?

**Review by gheorghelupu17 — CHANGES_REQUESTED** [review]
One more check pls

**Review by andreiio — APPROVED** [review]
Ar trebui să fie ok, the migration runs fine.

**Comment by sherbastian** [comment]
intra sau il anulez? vad ca are wontfix

**Comment by sherbastian** [comment]
i-am dat o cheie pe local, tipurile se schimba corect & it worked

**Comment by andreiio** [comment]
Intră imediat, thanks!

**Pull request merged**
