### PR TITLE
trusted user - create help request user errors

### PR DESCRIPTION
**Pull request by beniamin**
… by a trusted user

### Requirements for making a pull request

Thank you for contributing to our project! 

Please fill out the template below to help the project maintainers review it as fast as possible and include your contribution to the project.

### What does it fix?

Keep create user modal visible if there are validation errors from trusted user create help request page.

### How has it been tested?

Please describe the tests that you ran to verify your changes.

- create help request as a trusted user
- create help request as a refugee user

### CODE REVIEW

**Comment by idormenco** [comment]
Issues found
- [ ] when ask for accommodation and registering with an existing email error message says `The new user.email has already been taken`
- [ ] when offer accommodation and none of the fields are filled in validation takes place on server (can we have it on client?) 
- [ ] when offer accommodation and none of the fields are filled error messages are wrong  see screenshot 
image
 

not related to your PR:
Age should be numeric

**Comment by beniamin** [comment]
> * when ask for accommodation and registering with an existing email error message says `The new user.email has already been taken`

Taking into consideration the intent of the form is to create a new user, I think this is a normal behaviour. We should not allow 2 users having same email address.
Probabil we will need a "search user" box, besides create user button, to be able to add multiple accommodations for same host.

**Comment by beniamin** [comment]
> * [ ]  when offer accommodation and none of the fields are filled in validation takes place on server (can we have it on client?)
> * [ ]  when offer accommodation and none of the fields are filled error messages are wrong  see screenshot

Can we open a different issue for these problems? I don't know how easy it is to fix them and I think we should not block this PR, because the the current behaviour of the help request create user modal is counter-intuitive if errors are encountered.

**Review by andreiio — APPROVED** [review]
Looks good to me.

Validation on client ar fi un nice to have pe viitor.

**Pull request merged**
